### ISSUE TITLE
Tasks Window

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#1]
The task entry window is a bit small but one can make it bigger - but then the window can be made bigger than the overall window and the right hand side of the window goes out of site and is difficult to get to.  Would it be better to have a fixed window with good width but scrollabe vertically.
![tasks windows](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/15215377/2ec010fd-0d1b-414e-9898-e3eff0f0c933)

**Comment by SystemSculpt** [comment]
Fixed in the next update 👍
