### ISSUE TITLE
Models not showing

### ISSUE THREAD

**Issue by munish259272** [SystemSculpt/obsidian-systemsculpt-ai#12]
I do not see any local models for selection

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/834673/667717c4-0ce6-472d-be17-2ed2cdb4a946)

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/834673/8386dfd0-ffd2-46a3-aedc-75e0e5166a50)

**Comment by SystemSculpt** [comment]
Hi - have you tried restarting the Obsidian application? I think there's a bug where specifically for local models, the first time they are loaded in, it requires a restart. I'll fix this in the next update, but this should be a workaround for now

**Comment by munish259272** [comment]
Ok, i restarted it twice or 3 times i think and also disbaled enabled cross origin requests and somehow i can see it.
I am not sure what was the issue but it seems to detect now 

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/834673/f13de15d-d3e4-4b80-a85e-d8d94720d5a2)

Thanks for replying

**Comment by SystemSculpt** [comment]
great, I'm glad you can see it now - I will diagnose and figure out this issue and add it to the next update's fixes. I really appreciate your bug report here, I'll keep this open until this issue is resolved. Cheers!

**Comment by SystemSculpt** [comment]
Fixed in update later today.
