### ISSUE TITLE
Interference with Developer Console and Handlebars.js Functionality

### ISSUE THREAD

**Issue by RitchieMatt** [SystemSculpt/obsidian-systemsculpt-ai#13]
### Issue Summary:
When the System Sculpt AI plugin is enabled in Obsidian, it interferes with the Developer console. Specifically, it stops console.log messages from other plugins and prevents the use of variables when getting or setting with Handlebars.js.

### Steps to Reproduce:

1. Enable the System Sculpt AI plugin in Obsidian.
2. Attempt to log messages using console.log from another plugin.
3. Try to use variables with Handlebars.js for getting or setting values.

### Expected Behavior:
- console.log messages from other plugins should be visible in the Developer console.
- Variables should be usable with Handlebars.js without any issues.

## Actual Behavior:
- console.log messages from other plugins do not appear in the Developer console.
- Variables cannot be used effectively with Handlebars.js, disrupting functionality.

## Environment:
Obsidian version: v1.6.5
System Sculpt AI plugin version: 0.4.7
Operating System: Ubuntu 22.04

#### Additional Information: 
Disabling the System Sculpt AI plugin resolves the issue, indicating a conflict between the plugin and the Developer console/Handlebars.js functionality.

**Comment by SystemSculpt** [comment]
Great catch; one of the blindspots since I always have dev mode enabled. I'll have this fixed in the next update :)

**Comment by SystemSculpt** [comment]
Fixed in update later today.
