### ISSUE TITLE
OpenRouter Model Options not Turning off Wen OpenRouter not Selected

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#14]
Even after a shut down restart, having disabled it, the model list still appears and a model can be selected.
{Should there be a way to make OpenRouter easier to use, the list available is long and it would be good if one could enable only a few of the coices.}

**Comment by SystemSculpt** [comment]
This issue is fixed in the upcoming update later today. Cheers!
