### ISSUE TITLE
Does this plugin work with local LLMs and front ends such as Ollama or is it strictly OpenAI?

### ISSUE THREAD

**Issue by richardstevenhack** [SystemSculpt/obsidian-systemsculpt-ai#15]
This is why we need better documentation. There's zero mention of local LLMs. I suspect many people who are using all the other Obsidian LLM plugins, since most of them do support local LLMs (however haphazardly) would agree that access to local LLMs from a privacy standpoint is useful.

**Comment by richardstevenhack** [comment]
Never mind. Already determined it does nothing with OpenAI. If one even wanted to use OpenAI, there's no indication where to insert API keys or anything. This is not a usable plugin at all without MUCH more documentation. The couple videos I looked at show nothing useful.

**Comment by SystemSculpt** [comment]
Hi! Thanks for your input - documentation will be going live today on the new website, so hopefully that helps out a lot. In the meantime, if you look at the SystemSculpt Settings, you should see 4 available "API Endpoints", or access points, that you can connect an LLM with:

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/146425971/d550dd9f-0644-4aec-a5c1-56503afe02b3)

Again, this will be more evident and easier to follow in the documentation I upload later today. Cheers!

**Comment by richardstevenhack** [comment]
My problem is: there is no such thing as SystemScuplt Settings in my installation on Obsidian except for the hot keys settings. I don't see anything like you show in the image above.  That's the problem. I'm over at the Discord now to ask about that.

**Comment by richardstevenhack** [comment]
For those who may read this, it's a problem with my vault. Installing in the Obsidian sandbox vault lets it work. Now I have to debug my vault. (sigh)
