### ISSUE TITLE
Please add a custom baseURL to access more models.

### ISSUE THREAD

**Issue by Wooden-Gear** [SystemSculpt/obsidian-systemsculpt-ai#16]
Please add a custom baseURL to access more models.

**Comment by Wooden-Gear** [comment]
Hi! Could you provide me with a few more details for this? For instance, an example of the base URL you wish to use, thanks!

It's enough to be compatible with OpenAI, as many models are compatible with OpenAI.

**Comment by SystemSculpt** [comment]
I still don't understand - currently SystemSculpt allows for using OpenAI, OpenRouter, Groq, and local models. I'm going to need an example of a use case of the feature you're asking for so that I can use that example to better implement what you're requesting - otherwise I'm in the dark on this one.

**Comment by Wooden-Gear** [comment]
> I still don't understand - currently SystemSculpt allows for using OpenAI, OpenRouter, Groq, and local models. I'm going to need an example of a use case of the feature you're asking for so that I can use that example to better implement what you're requesting - otherwise I'm in the dark on this one.

![screenshot](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/143693404/e6469d44-08e9-497c-8b33-7aafab2f5daf)

This is the custom model setup for the Text Generator.

**Comment by SystemSculpt** [comment]
Ahhhh, I understand now. Thanks for the clarification, will add this feature

**Comment by whshang** [comment]
When will this update be available?

**Comment by SystemSculpt** [comment]
Hi everyone, this will be implemented/part of this upcoming Friday's massive update. I will close this once it's in production version :)
