### ISSUE TITLE
Momentary issue of version 0.1.1

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#17]
I checked on my mobile while eating breakfast seemed to be a version 0.1.0 but then it dissappeared by the time I got to my desk.  Did I miss seee or was I momentarily in an alternative universe? (Or just suffered a Biden (senior) moment?

**Comment by SystemSculpt** [comment]
Hahaha, weird though, was this on your mobile device? Because there's no mobile version yet, maybe that's where the glitch came from - desktop version is still 0.4.7 :) update later today though!

**Comment by grayerbeard** [comment]
I think it must have been either a time warp or a brain malfunction.
