### ISSUE TITLE
Max Tokens Can't Be Changed Or The Change Can't Be Saved

### ISSUE THREAD

**Issue by 3-ark** [SystemSculpt/obsidian-systemsculpt-ai#18]
## Describe the bug
Under 'Brain' the 'max tokens' can't save the change.
## Environment
- OS: windows
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
1. change the number of tokens 2. Click out 3. Check max tokens again.

**Comment by SystemSculpt** [comment]
Seems to work just fine for me - are you attempting to save something over 4096? Because it will auto-correct to the maximum of 4096 output tokens by default.

**Comment by SystemSculpt** [comment]
Ah, seems like you're confusing max context length with max tokens output. I should clarify better the namings/differences, but for your current reference, max tokens are what the model is able to generate back to you, and all models (that I currently know of) cap out at 4096 tokens generated back in 1 request.
