### ISSUE TITLE
Chat Folder Cannot Be Changed Effectively

### ISSUE THREAD

**Issue by 3-ark** [SystemSculpt/obsidian-systemsculpt-ai#19]
## Describe the bug
I changed the default folder to mine, and it saved after the change. But when I start a new chat, then it will create a folder and notes as the initial setting.  

## Environment
- OS: windows
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
Just create a new chat after changing the folder. Maybe this is also relevant, I added context note to the chat.

**Comment by SystemSculpt** [comment]
Thank you for this, I fixed it just now thanks to your report. Will be part of next update soon. Cheers!
