### ISSUE TITLE
Does it supports gpt4 or gpt4o

### ISSUE THREAD

**Issue by munish259272** [SystemSculpt/obsidian-systemsculpt-ai#25]
![image](https://github.com/user-attachments/assets/2ec0e5c0-e943-48e8-b82f-206d882901d6)

It only shows gpt-3.5  which ones can i select or it only supports gpt-3.5

Open ai has these models
![image](https://github.com/user-attachments/assets/ea4cca98-e91b-425b-87f4-126cf9ae5c75)

**Comment by SystemSculpt** [comment]
Interesting; have you paid enough to be in Tier 1 for OpenAI? See images below:
![image](https://github.com/user-attachments/assets/9234b83c-9f82-49c7-876e-50afc0a02592)
![image](https://github.com/user-attachments/assets/a98e842e-b6fa-4744-91e6-c4217c2e7a7f)

If yes, you've used your API key to use gpt-4 / gpt-4o successfully elsewhere, let me know and I will diagnose further. Thanks!

**Comment by SystemSculpt** [comment]
https://platform.openai.com/settings/organization/limits

**Comment by munish259272** [comment]
Yes, i have access and it has detected now.

I have allowed these models ?
![image](https://github.com/user-attachments/assets/9ea129c5-7e0b-407a-bd67-0642fd7b1c36)

![image](https://github.com/user-attachments/assets/bebe2ac6-9bbd-4851-b968-02fcfd94b1ce)

**Comment by SystemSculpt** [comment]
OK cool, seems like it works for you now :) and I will have the mini model implemented soon, just some final tests going on in the background
