### ISSUE TITLE
Request: Transcription prompt

### ISSUE THREAD

**Issue by ChrisBBBB** [SystemSculpt/obsidian-systemsculpt-ai#3]
I've just been testing the recording audio function, it's really good. I'm assuming that you're using the Whisper model for the transcription? Whatever the model is, can you give us access to a prompt, so that we can customise the prompt that gets used?

It's really good in your 'brain settings' you allow the user to modify the prompts that are used, but I'd like the same with the transcription also please. I like to specify exactly how I want my output written, and the particular dialect of spelling of the words that I'm dictating. Also, the Whisper prompt allows the user to provide words with difficult spellings or unusual pronunciations, to give the model a better chance of getting the word right (the Obsidian Whisper plugin, does this nicely).

Thanks
Please keep up the good work.

**Comment by SystemSculpt** [comment]
Will look into implementing this in the next update after local LLM :)

**Comment by SystemSculpt** [comment]
Just implemented this in version 0.6.7, let me know what you think and what other changes you'd like to see (as a new github issue, if you do find something to add/edit)
