### ISSUE TITLE
I Can't Use The Model In Lm Studio After The Last Updates

### ISSUE THREAD

**Issue by SleepingSmel** [SystemSculpt/obsidian-systemsculpt-ai#32]
## Describe the bug
Before I could, but know even chengeing the port it's impossible! (great work you're doing with tis plugin, it's amazing and I'm missing it hehe)

## Environment
- OS: windows
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
Try to use it locally with LM Studio

**Comment by SystemSculpt** [comment]
Should be fixed now with latest 0.5.3 update :) if not, let me know by re-opening/creating a new issue. Thanks and enjoy!
