### ISSUE TITLE
recorder bug

### ISSUE THREAD

**Issue by ttodosi** [SystemSculpt/obsidian-systemsculpt-ai#34]
found a bug in the recorder 
if you turn off the saving of audio files it doesn't transcribe

**Comment by SystemSculpt** [comment]
Thanks for the insight, will fix this in next update! Keeping this issue open until the update hits.

**Comment by SystemSculpt** [comment]
hey, just fixed this bug. transcription now works correctly whether you're saving audio files or not. it'll be in the next update (v0.7.0) coming out later today. thanks for pointing this out!
