### ISSUE TITLE
Impossibility To Make Chaptgpt Answer Me In My Obsidian (With Systemsculpt Ai).

### ISSUE THREAD

**Issue by BraksWord** [SystemSculpt/obsidian-systemsculpt-ai#37]
## Describe the question
Even though I use the correct API (i think), I have the latest version of obsidian and the plugin. I have an issue: I never get an answer from GPT in the conversation. Thanks for your answer.

**Comment by Daryl-Horton** [comment]
I'm having the same issue. I'm using a localhost via LMStudio. Everything is properly configured and was working just fine until the most recent updates. Now there is no response when using the chat.

**Comment by SystemSculpt** [comment]
Interesting; I will look into this and do testing with new vaults/configurations to see what the problem is. Have either of you tested/tried it out on the latest 0.6.2 update to see if it's resolved?

**Comment by Daryl-Horton** [comment]
i had the update, but chat wasn't working until i closed the chat and used the command palette to open a new chat. works now. thanks.

**Comment by BraksWord** [comment]
> Interesting; I will look into this and do testing with new vaults/configurations to see what the problem is. Have either of you tested/tried it out on the latest 0.6.2 update to see if it's resolved?

It isn't. I guess I'm doing something wrong. With the new version I opened a new chat, ask something, it doesn't answer. Maybe it comes from my gpt API that isn't correct ? But from what I see it isn't the case either. Could you help me out maybe ?

**Comment by SystemSculpt** [comment]
Hi @BraksWord - I'm going to need more details to help you out. Which endpoint are you using, OpenAI / Grok / OpenRouter / Local? Which model? If you're using an API, do you have enough purchased credits with that API provider in order to use it? A screenshot or a few would really help out here. Has it worked in the past? Etc.

**Comment by BraksWord** [comment]
Hey, @SystemSculpt thx for helping me. There are as much information as I can give you.
I use Open AI, I get the API there (see picture below), (FYI, I'm not paying anything, and I think the problem might come from here ?). 
It has never worked in the past by the way, and here is what it looks like (another picture below).

But, the fact that I can see a price, and that you asked me if I had purchase credits (and I didn't), make me think that I was the problem 😅 I thought I could Open AI inside Obsidian, like with chat GPT...😅
<img width="1440" alt="API open ai" src="https://github.com/user-attachments/assets/eb3e63ce-91fe-444a-8ac0-aec87551f83c">
<img width="437" alt="Chat exemple" src="https://github.com/user-attachments/assets/983a0aba-19b9-4a39-a850-e63e1a20b073">

Thank you
