### ISSUE TITLE
Add Default Language Selection For Recorder

### ISSUE THREAD

**Issue by alexey-ezhikov** [SystemSculpt/obsidian-systemsculpt-ai#38]
## Describe the enhancement
OpenAI Whisper sometimes hallucinates on short audio clips and wrongly detects speaker's language. It's easy to add another setting to the Recorder tab where one can select or input the default language for speech recognition.

**Comment by SystemSculpt** [comment]
Great addition, I will be adding this - keeping this opened until it's implemented.

**Comment by ChrisBBBB** [comment]
I think this is closely related to the enhancement request I made in [issue #3](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/issues/3#issue-2254664176) to have access to the Whisper prompt.
I don't know if the language setting is a different parameter but if we would be able to set the language and the Whisper prompt that would help us make full use of Whisper's capabilities via SS. Many thanks.

**Comment by SystemSculpt** [comment]
Hi @alexey-ezhikov, thanks for the suggestion! I’ve added the default language selection to the recorder settings, with English as the default option. This feature is available starting with the 0.7.0 update going live tonight. Additionally, there’s now more control over the transcription process, including fixing niche/personal vocabulary words, spellings, and post-processing. I’ll go ahead and close this issue. Let me know if you need anything else :)
![image](https://github.com/user-attachments/assets/53def2d6-992e-4ca3-aec4-c2f4a89bc28f)
