### ISSUE TITLE
AI Using Template Suggestion

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#4]
I used my fabric_get_instructions template to get instructions from a video.
Worked OK with this procedure;

- Press Alt N to choose template.
- Choose my Template (basd on a fabric template) for getting instructions from a YouTube Video.
- Went to youtube and copied the transcript
- Pasted in at end of template
- Pressed Alt L (The Hotkey I had set for "SystemSculpt AI: Toggle general generation" )

Result ; I now have a Note File With the required result at the end but still have the template at start.

SUGGESTION:
 Would prefer to somehow do something more like this:

Put the YouTube transcript in a Note and enter its File Name (This could also be some other prompt for AI) 
Enter somewhere what Template to use
Then Just Hit a Hotkey and the AI would generate a new file based on the Transcript and the Template, with an automaticly generated title.

I suspect you maybe working on something like this but I feel current procedure is improvable..

Template Used:
[fabric_get_instructions.md](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/files/15095544/fabric_get_instructions.md)

Result:
[Setting Up SystemSculpt AI with BRAT on Obsidian A Step-by-Step Tutorial.md](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/files/15095635/Setting.Up.SystemSculpt.AI.with.BRAT.on.Obsidian.A.Step-by-Step.Tutorial.md)

**Comment by SystemSculpt** [comment]
Yep, I have YouTube video transcription in the works as part of the upcoming new Data module, will have that + Omnivore + Readwise + Reader integration to start with, maybe Twitter too if I have time to add that before I release the initial version of it :)

**Comment by grayerbeard** [comment]
I think that is great and there is just one request I have just thought of…..

 

If you could figure out how to answer a question about your plug in using AI from within Obsidian.. “How do I …”, “I want to ….. but instead … how do I fix” etc.  You could build in an attempt at this and ask users to tell you if they don’t get a good answer so then make it self improve.    Its an important step towards the totally intuitive AI where learning how to set up a plug in is totally painless!!  (Would be a great help for my decaying 74 year old brain!!)

 

By the way I got the local LLM working really well yesterday, I was using Llama 3 and it was really fast.  My only difficulty was issues with context windows and long questions getting short answers.   When using OpenAI you have a context window setting.  In LM Studio I used to be able to mess with that and some Models had big windows – you have done a lot of testing so at some point some sort of write up – or a remake of some of your old videos – looking at how to tackle your Plug in plus LM Studio – which Models best for what etc would be great (and how to tweak) .   – A future wish though you need to get the functionality going first.

 

Regards

David Torrens

Grayerbeard

Shropshire UK
