### ISSUE TITLE
Imposibility to Paste Any Text in The Chat

### ISSUE THREAD

**Issue by febilogi** [SystemSculpt/obsidian-systemsculpt-ai#40]
I can't paste any text into the chat after updating the system sculpt plugin to version 0.6.0. I can still copy text from the chat box and paste it elsewhere, but I can't paste text back into the chat.

However, pasting works normally in other (note) windows and the sidebar. I checked the settings but couldn't find a solution or toggle to fix this issue. 

I am using a Windows laptop.

**Comment by SystemSculpt** [comment]
Thanks for catching this problem so quick, just fixed it in a speedy 0.6.1 update! Cheers

**Comment by febilogi** [comment]
But the 0.6.1 isn't public yet, right? I can't update it yet even though I already get the notification that v0.6.1 is ready after I restart my obsidian. Probably it needs some time. In the picture we could see there isn't any option to update it yet.

![image](https://github.com/user-attachments/assets/a85c5f61-3406-4b38-81cb-817df3a8001c)

**Comment by febilogi** [comment]
It's already public and it works normally. Thank you so much!
