### ISSUE TITLE
Cosmetic Recommendation: Aligning JUST The User Chat Bubble to The Right, Not With The Text 

### ISSUE THREAD

**Issue by febilogi** [SystemSculpt/obsidian-systemsculpt-ai#41]
The AI's chat bubble functions effectively, enabling deletion, copying, and maintaining a left alignment for a natural reading flow. However, there is room for improvement in the user chat bubble. While right alignment is necessary to distinguish the message sender, I recommend right-aligning only the bubble itself while keeping the text within the bubble left-aligned. This adjustment would enhance readability and user experience.

Reasons why left-aligned text is preferable:
1. **Readability**: Left-aligned text is easier to read for most languages that read from left to right, as it creates a consistent starting point for each line.
2. **Natural Flow**: Left alignment follows the natural flow of reading, making it more intuitive and comfortable for users.
3. **Visual Hierarchy**: Left alignment helps establish a clear visual hierarchy, guiding the reader's eye through the content.
4. **Design Consistency**: Many design standards favor left alignment for text, making it a familiar and expected format for users.

If you feel this is unnecessary, feel free to delete this issue :D as always, you have a great plugin that helps thousands of people. I pray that you are healthy, prosperous, and at peace.

**Comment by SystemSculpt** [comment]
Agreed with you; I'll fix this and many other visual updates to the chatview in the upcoming update. Keeping this open until it's implemented.

**Comment by SystemSculpt** [comment]
Done and dusted, will be live with the next update in a few hours. Thanks so much for the enhancement recommendations febilogi! 🫡 ❤️
