### ISSUE TITLE
Popup for 0.6.1 update yet no update available according to Obsidian

### ISSUE THREAD

**Issue by niesink** [SystemSculpt/obsidian-systemsculpt-ai#44]
Today I keep getting the popup below, yet in Community Plugins Obsidian tells me there are no plugin updates found and 0.6.0 is the latest version. I've already restarted Obsidian multiple times.

> A new version of SystemSculpt AI (0.6.1) is available. Please update the plugin through Community Plugins to get the latest features, fixes, and improvements.

**Comment by SystemSculpt** [comment]
This should be solved with the latest 0.6.2 update, apologies for the confusion/glitch. Thanks for letting me know!
