### ISSUE TITLE
Issues with Chat and context files 0.6.2

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#45]
I am having all sorts of issues with chat and context files.  I add a file then it disappears.  I try to add a file and it seems not to be added. I try to copy past from a chat to a note and strange things happen.  I try to scroll up click "previous message" looking at earlier parts of chat and the chat resulats dissappear.
I think a bug or bugs has crept in and/or the software was tested by doing things in a certain order and I am being awkward by using chat a bit differently.
I am using 0.6.2 in Win 11. using a large context file containing a YouTube transcript from a recent Trump speech and asking Anthropic to convert it into coherant understandable english.
A difficult task that may just be too much.

Another example:
I had downloaded the Transcript of a YouTube Video to use as Context file for a Prompt.
Then I posted at Question to the AI in Chat on how to write a Prompt that would fairly analyse the Transcript. (Make sensce of it)
Then I had the responce for the prompt
Then I clicked to Symbol at the Top Left to create a new Note to put the responce into.
It then appearsd at first that my Chat conversation had disaappeared.
BUT it hadnet it had been acrvchived into a new note.

I think my problem is that the system is set up to approach using chat in a particular way - perhaps chat should be nore tolerant of deviant behaviour or mayby when it does something like clearing chat and archiving old it should tell you (maybe when set ina verbose setting that could be trurned off when one is used to it)

Otherwise there is a big risk of new users being very confused by what is in fact a clever idea to try to smooth the flow.

**Comment by SystemSculpt** [comment]
#48 conversation/solution/update talk moved to there :)
