### ISSUE TITLE
Bug:  No "Default Model" without a Groq key 

### ISSUE THREAD

**Issue by grayerbeard** [SystemSculpt/obsidian-systemsculpt-ai#6]
After updating to version 3 I tried to select the Default Model. (Had been set on GPT 3.5 turbo I wanted GPT 4) the word "cycling" appeared then it went blank.  I have no local model running at the moment and I only have an OpenAI Key set no Groq key.

If I restart Obsidian it goes back to GPT 3.5 and AI chat does work but if I try again to change default model same happens again.  So now I am stuck on 3.5 which is working.

**Comment by SystemSculpt** [comment]
Hi!

Do you have it enabled?

![image](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/146425971/bb80dc3d-6c25-4d85-adcd-c621d9857bb4)

**Comment by SystemSculpt** [comment]
(Default models will only show if you have them toggled on, this feature is because now you can decide to ignore certain models and toggle between only ones that you want to use instead of having to cycle through all of them)

**Comment by grayerbeard** [comment]
But if you try to change it when only OpenAi is available it goes blank.  It appears, in my case, I cannot change from gpt 3.5 to gpt 4.

**Comment by grayerbeard** [comment]
I was not aware of that screen, I will check into it when I next get to my Laptop (in few hours) and report back.

Shouldn't some message appear to direct me to it ?

DT

**Comment by SystemSculpt** [comment]
Hey, thanks for the insight - though I am not sure where to set up a message; I put the setting right under the default model so that it's as apparent as possible for the user to select which models they want to utilize - I'll try playing with colors and a different look to make it pop out more. Cheers!

**Comment by grayerbeard** [comment]
Sorry My Mistake.    I think it would be marginally better if that little Wiindow that show Default model said Something like "See Below ..." idf no model is selected.  No Issue now now I have discobvered the wonders that appear when you scroll down.

By the way Grok is not available yet in UK although it does seem interesting and very usefull based on reading blurb on website.

**Comment by grayerbeard** [comment]
Ref "Apparentness".  Try it on a lower Def screen on my screen you only see all that lovely model selection stuff if you scroll down.

**Comment by jthomaskerr** [comment]
I am seeing a similar issue whenever local ai is enabled. At a guess I think that there may be an error in parsing the model list. This is the response of lmstudio:

```
curl http://192.168.0.100:1234/v1/models
{
  "data": [
    {
      "id": "TheBloke/una-cybertron-7B-v2-GGUF/una-cybertron-7b-v2-bf16.Q5_K_S.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    },
    {
      "id": "nomic-ai/nomic-embed-text-v1.5-GGUF/nomic-embed-text-v1.5.Q8_0.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
}
```
![Screenshot 2024-05-20 132240](https://github.com/SystemSculpt/obsidian-systemsculpt-ai/assets/903987/cdd55184-e696-40db-bef4-31b0eeca1de7)

**Comment by jthomaskerr** [comment]
In my case this appears to be a CORS issue. I had to turn that setting on in LMStudio

**Comment by SystemSculpt** [comment]
> In my case this appears to be a CORS issue. I had to turn that setting on in LMStudio

Thank you for this observation; I'll be sure to add a check / notification for the user to make sure their CORS is set to on. Cheers and I hope it works well for you now!
