### ISSUE TITLE
No Bug, But Makes The Ai Unusable For Me

### ISSUE THREAD

**Issue by MichaelHHeng** [SystemSculpt/obsidian-systemsculpt-ai#62]
## Describe the bug
Templates → Trigger key: There is no key that I could use there that I would not also use in my normal texts. The default key always triggers the dialogue when I enter for example dog/cat, which is then no longer possible. I use ‘/’ all the time. But since I can't delete the key and I haven't found a key that I don't need and this dialogue, which I don't want, keeps popping up, I unfortunately have to deactivate the plugin completely. 🤷‍♂️ The option to deactivate this dialogue would solve the problem (at least superficially).

## Environment
- OS: macos
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
See description

**Comment by SystemSculpt** [comment]
OK, so I think an easy way to fix this would be to add functionality where if you leave the trigger field blank in settings, it disables the pop up for you. I've just implemented this fix as I'm typing out this reply to you
