### ISSUE TITLE
Api Key Reset

### ISSUE THREAD

**Issue by Bsaubolle** [SystemSculpt/obsidian-systemsculpt-ai#65]
## Describe the bug
Each time I reload the app, either from an Obsidian command or when I restart my computer, I have to re-enter the API key.

## Environment
- OS: linux
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
Enter API key, close Obsidian.

**Comment by SystemSculpt** [comment]
Fixed in the next update, thanks for letting me know! Next update will be live in a few hours from the time of this message.
