### ISSUE TITLE
Custom Templates Not Loading

### ISSUE THREAD

**Issue by Bsaubolle** [SystemSculpt/obsidian-systemsculpt-ai#66]
## Describe the bug
I create a markdown file in the specified Template directory (the default, which is "SystemSculpt/Templates"). When using either the command palette or slash, it only shows "Blank Template" as an option. 

## Environment
- OS: linux
- SystemSculpt AI Version: Latest (Please ensure you're using the latest version before submitting)

## To Reproduce
Initialize SystemSculpt -> Create a template note as a Markdown file -> place note in Template directory -> go to a note you'd like to "chat with" or "process" with an LLM -> use the slash command or command palette to quickly recall a prompt.

## Questions
Is there specific frontmatter/YAML that I need to include in Properties? I looked through the documentation and couldn't find if I needed to add a property to trigger its inclusion in the templates.

**Comment by SystemSculpt** [comment]
Hi! Please look at https://www.systemsculpt.com/docs/templates-module-docs/templates-customization of the documentation to see specifics on what's required in the template and how to allow SystemSculpt AI to recognize it correctly :)

**Comment by Bsaubolle** [comment]
Ah! Apologies for missing this, I was only looking at the Usage docs. Thank you!
