### ISSUE TITLE
Context is not being undestood by gpt

### ISSUE THREAD

**Issue by CGAlei** [SystemSculpt/obsidian-systemsculpt-ai#7]
Hi thanks for your great work!

here is my inference with  gpt3turbo

Here's a summary of my expenses:

* Rent: $350 per month
* Food: $100 per month
* Communications: $50 per month
* Medicine: $50 per month

Total monthly expenses: $550

if my rent goes down to $200 per month, because i found a cheaper place how much will be my complete (food, comm,medicine) expenses untils end of year, being May the current month.

If your rent decreases to $200 per month, your total monthly expenses would be reduced to $400. From May until the end of the year, considering the current month as the starting point, you would have seven months left. Therefore, the total expenses for food, communications, and medicine for the remaining months would sum up to $2,800 ($400 * 7 months).

in chatpt the answer is correct

**Comment by SystemSculpt** [comment]
Interesting; are you using gpt 3.5 or 4o? Also, gpts aren't necessarily good at math; calculations are bound to be off usually especially if you're factoring in many numbers altogether. They're much more useful as word processors rather than calculator replacements
