### ISSUE TITLE
Request - Recorder: paste text before AND after post-processing

### ISSUE THREAD

**Issue by ChrisBBBB** [SystemSculpt/obsidian-systemsculpt-ai#71]
I think it's absolutely great you added the Whisper prompt function and then allowed a post-processing prompt. This is a step change in the way that people can use the recorder function. Thanks so much. 

Two points. (1) My understanding is the 'Whisper prompt' is not really a prompt. It's a list of favored words to use as examples for the transcribing AI. Your example is perfect, but all of your explanation text called it a 'prompt' and people might think that they can enter commands in it; and it doesn't work like that. I don't think it might be helpful for those who are not expert in this if you called it something else or provided a small explanation. 

(2) I am using a post-processing prompt and having some issues with it, it would really help debugging if SS showed me the before and after. So my request is an option that allows me to select if I want the raw transcript text pasted _**and then also**_ the post-processed text. Then I can see if something is going wrong in the transcription or going wrong in the post-processing. 

My specific example, by the way, I will mention in case anybody else is getting it too, is that my longer transcriptions since the 0.6 upgrade are 50% of the time coming out in a different language. When I put that foreign language through a translator it is indeed the text that I said, but I don't know whether it is the transcription that is translating it or whether it is my post-processing prompt that is translating it. Having the ability to optionally have _both_ pasted would help me work out what is going on. Or also maybe also give us the Whisper language field instead of letting it autodetect?

As always, many thanks for your work.

**Comment by SystemSculpt** [comment]
Thanks so much for your feedback, Chris! I've implemented the option to paste both the raw transcript and post-processed text, and updated the terminology for the 'Whisper prompt' to avoid confusion. These features are part of the 0.7.0 update, which will be live later today. I appreciate your help in improving the recorder! :)
