### ISSUE TITLE
Styles are leaking to quick switcher

### ISSUE THREAD

**Issue by ronilaukkarinen** [SystemSculpt/obsidian-systemsculpt-ai#76]
You should use more specific styles. Now they are leaking to other parts in the editor.

![image](https://github.com/user-attachments/assets/752826b7-406c-41b9-bd75-451f08681add)

https://github.com/SystemSculpt/obsidian-systemsculpt-ai/blob/041f7ccd3c95473281bb0459c1126271245171e7/styles.css#L913-L916

**Comment by SystemSculpt** [comment]
thank you for the suggestion, this is one of my top priorities in my major style overhaul, I want to prefix everything with systemsculpt before the actual class name

I'll keep this open until this is resolved

**Comment by SystemSculpt** [comment]
i've sorted out the css issues, should be working fine now. give it a try when v0.7.0 drops later today! :)
