### ISSUE TITLE
Add option to include the ai model/version in the chat outputs

### ISSUE THREAD

**Issue by ChrisBBBB** [SystemSculpt/obsidian-systemsculpt-ai#9]
I've been trying the chat feature and it is quite impressive I have to say. My **feature request** is that there is an option to enable the specific chat model and version to be included in the chat response text. 

I'd like to know which model I'm chatting with as I might be experimenting with several models and then days or weeks after the event I'm going to lose track of which model gave which responses. If an option for that that information could be included in the chat text output maybe. For example instead of it saying 'user' and 'ai' in the code block could it say AI-model-version. Many thanks for your work.

**Comment by josh-stephens** [comment]
I think naming the model in the chat is a great idea. If there was a way to estimate and track cost for generations, that would be really helpful as well.

**Comment by SystemSculpt** [comment]
just implemented both @ChrisBBBB chat feature request to see which model has answered, as well as @josh-stephens request for having a price estimator for each chat (the new little dollar bag icon button next to the token count). cheers!
